# Generated by Django 2.2.4 on 2019-10-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upccode', models.CharField(max_length=14, verbose_name='UPC code')),
                ('description', models.CharField(max_length=60, verbose_name='Description')),
                ('quantitiy', models.IntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Unit Price')),
            ],
        ),
    ]
